#!/bin/zsh

if [ '0' = "$#" ]
then
	clang++ -Wall -Wextra -Werror -I../utils -I../vector/ -I../vector/iterators/  main.cpp -o stack
fi
if [ '-g' = "$1" ]
then
	clang++ -g -fsanitize=address -I../utils -I../vector/ -I../vector/iterators/ main.cpp -o stack
fi


