#!/bin/zsh

if [ $# = "0" ]
then
	clang++ -Wall -Wextra -Werror -g -I../utils -Iiterators -I../vector/ -I../vector/iterators/ main.cpp -o redBlackTree
fi
if [ '-g' = "$1" ]
then
	clang++ -g -fsanitize=address -I../utils -Iiterators -I../vector/ -I../vector/iterators/ main.cpp -o redBlackTree
fi


#man getopts
