#!/bin/zsh

if [ $# = "0" ]
then
	clang++ -Wall -Wextra -Werror -I../utils main.cpp -o redBlackTree
fi
if [ '-g' = "$1" ]
then
	clang++ -g -fsanitize=address -I../utils main.cpp -o redBlackTree
fi


#man getopts
