#!/bin/zsh

if [ 'flags' = "$1" ]
then
	clang++ -Wall -Wextra -Werror -g -I../utils main.cpp -o redBlackTree
else
	clang++ -I../utils main.cpp -o redBlackTree
fi
if [ '-g' = "$1" ]
then
	clang++ -g -fsanitize=address -I../utils main.cpp -o redBlackTree
fi


#man getopts
