#!/bin/zsh

if [ '0' = "$#" ]
then
	clang++ -Wall -Wextra -Werror -Iiterators/ -I../utils main.cpp -o vector
fi
if [ '-g' = "$1" ]
then
	clang++ -g -fsanitize=address -Iiterators/ -I../utils main.cpp -o vector
fi


#man getopts
