#!/bin/zsh

if [ 'flags' = "$1" ]
then
	clang++ -Wall -Wextra -Werror -g -Iiterators/ -I../utils main.cpp -o vector
else
	clang++ -Iiterators/ -I../utils main.cpp -o vector
fi
if [ '-g' = "$1" ]
then
	clang++ -g -fsanitize=address -Iiterators/ -I../utils main.cpp -o vector
fi


#man getopts
